function safe = issafe1(reach,xr)

x = reach.X;
Xup = reach.Xup;
Xlow = reach.Xlow;
T = reach.T;
deltae = reach.deltae;
TT = reach.TT;
% load('xr(0.0.01.2).mat');
xr_last = xr(201,:);
safe = 1;
for i=1:size(x,1)
    if x(i,1)>25 || x(i,1)<0 || ...
            x(i,2)>pi/4 || x(i,2)<-pi/4 || ...
            x(i,3)>pi/2 || x(i,3)<-pi/2 || ...
            x(i,4)>3.5 || x(i,4)<-3.5|| ...
            x(i,5)>16 || x(i,5)<-3 || ...
            x(i,6)>10 || x(i,6)<-2
        safe = 0;
        return
    end
    if Xup(i,1)>25 || Xup(i,1)<0 || ...
            Xup(i,2)>pi/4 || Xup(i,2)<-pi/4 || ...
            Xup(i,3)>pi/2 || Xup(i,3)<-pi/2 || ...
            Xup(i,4)>3.5 || Xup(i,4)<-3.5|| ...
            Xup(i,5)>16 || Xup(i,5)<-3 || ...
            Xup(i,6)>10 || Xup(i,6)<-2
        safe = 0;
        return
    end
    if Xlow(i,1)>25 || Xlow(i,1)<0 || ...
            Xlow(i,2)>pi/4 || Xlow(i,2)<-pi/4 || ...
            Xlow(i,3)>pi/2 || Xlow(i,3)<-pi/2 || ...
            Xlow(i,4)>3.5 || Xlow(i,4)<-3.5|| ...
            Xlow(i,5)>16 || Xlow(i,5)<-3 || ...
            Xlow(i,6)>10 || Xlow(i,6)<-2
        safe = 0;
        return
    end
    for j = 1:size(TT,2)   %推力
        if TT(i,j)>8 || TT(i,j)<0
            safe = 0;
            disp('unsafe process T ');
            return
        end
    end
    for j = 1:size(deltae,2)    %舵偏角
        if deltae(i,j)>pi/3 || deltae(i,j)<-pi/3
            safe = 0;
            disp('unsafe process deltae ');
            return
        end
    end
    if   abs(Xup(i,1)-xr_last(1,1))<0.5 &&...
            abs(Xup(i,5)-xr_last(1,5))<0.15 && ...
            abs(Xup(i,6)-xr_last(1,6))<0.15 && ...
            abs(Xlow(i,1)-xr_last(1,1))<0.5 && ...
            abs(Xlow(i,5)-xr_last(1,5))<0.15 && ...
            abs(Xlow(i,6)-xr_last(1,6))<0.15
        return
    end
end
tolerance = 1e-4;
indice = find(abs(T - 2) < tolerance);
if   Xup(indice,1)-xr_last(1,1)>0.5 || Xup(indice,1)-xr_last(1,1)<-0.5 || ...
        Xup(indice,5)-xr_last(1,5)>0.15 || Xup(indice,5)-xr_last(1,5)<-0.15 || ...
        Xup(indice,6)-xr_last(1,6)>0.15 || Xup(indice,6)-xr_last(1,6)<-0.15|| ...
        Xlow(indice,1)-xr_last(1,1)>0.5 || Xlow(indice,1)-xr_last(1,1)<-0.5 || ...
        Xlow(indice,5)-xr_last(1,5)>0.15 || Xlow(indice,5)-xr_last(1,5)<-0.15 || ...
        Xlow(indice,6)-xr_last(1,6)>0.15 || Xlow(indice,6)-xr_last(1,6)<-0.15
    safe = 0;
    return
end
end